name:                text-mining
version:             0.1.0.0
github:              "alx741/text-mining"
license:             BSD3
author:              "Daniel Campoverde"
maintainer:          "alx@sillybytes.net"
copyright:           "2019 Daniel Campoverde"
synopsis:            Basic Text Mining
category:            Text, Machine Learning
description:         Please see the README on GitHub at <https://github.com/alx741/text-mining#readme>

extra-source-files:
- README.md
- ChangeLog.md


dependencies:
- base >= 4.7 && < 5
- text
- vector
- probability
- containers
- unordered-containers
- safe

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  text-mining-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - text-mining

tests:
  text-mining-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - text-mining
    - hspec
